version: "3"
services:
  mongodb:
    image: "mongo:4.2.12"
    volumes:
      - ./.docker/mongodb/data:/data/db
    ports:
      - 27017:27017
  app:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    user: 1000:1000
    volumes:
      - ./src:/var/www/html
      - ./.ci/local/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./.ci/local/ports.conf:/etc/apache2/ports.conf
      - ./.ci/local/interface.conf:/etc/apache2/sites-enabled/interface.conf
    #  environment:
    #    XDEBUG_CONFIG: client_host=${MYIP}
    #    DEBUG: 1
    depends_on:
      - mongodb
    ports:
      - 9050:9050

