<?php

namespace TelegramBot\Message\Text\Infrastructure\Providers;

use Illuminate\Support\ServiceProvider;

class MessageTextServiceProvider extends ServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
